---
# Same as v6, but has asymm_overlapping=False! Meaning it's something in between symm_chamfer_v1 and asymm_chamfer_v6, to fully ablate each addition.
batch_size: 32
extra_data: 
  - orientnorm
weight_orient: 0.25
lambda_points: 4
overlapping: 1

loss:
  - asymm_v6_chamfer_with_stroke_masks  # temp method that explicitly computes all asymm_v6 loss terms
weight_asymm_segment_chamfer: 1.0
weight_reverse_asymm_point_chamfer: 100
weight_reverse_asymm_segment_chamfer: 0.01
asymm_overlapping: false

# Decrease the weight_reverse_asymm_point_chamfer by *_factor, every *_freq epochs
# weight_scheduler_factor: 0.1  # deprecated
# weight_scheduler_freq: 300    # deprecated

psacd_scheduler:
  active: true
  factor: 0.1            
  freq: 1600            # overwritten by sched_v* files
  milestones: null

eval_ckpt: last