---
# From jointCategory-1-2-3 to containers_v2, FROM SCRATCH
# (it's important to use this config instead of simply containers_v2,
# as the data_scale_factor and other parameters should be the same for PCD comparison with the pretrained fewshot version)
dataset: containers-v2
data_scale_factor: 776.1721217165386
n_pred_traj_points: 3800
max_n_strokes: 41
batch_size: 64

model:
  pretrained_custom: null